# Generated by Django 3.2 on 2021-04-19 17:04

from django.db import migrations, models
import django.db.models.deletion
import geo.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.SlugField(max_length=2, primary_key=True, serialize=False, validators=[geo.validators.validate_numeric])),
                ('nom', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('code', models.SlugField(max_length=3, primary_key=True, serialize=False, validators=[geo.validators.validate_numeric])),
                ('nom', models.CharField(max_length=32)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.region')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('code', models.SlugField(max_length=5, primary_key=True, serialize=False, validators=[geo.validators.validate_numeric])),
                ('nom', models.CharField(max_length=255)),
                ('nom_norm', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.departement')),
            ],
        ),
        migrations.CreateModel(
            name='CodePostal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5, validators=[geo.validators.validate_numeric])),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.commune')),
            ],
            options={
                'verbose_name_plural': 'Codes Postaux',
                'unique_together': {('code', 'commune')},
            },
        ),
    ]
